Global Vertex v, w, farthest
Global Tree T
Global Int maximum

Function diameter() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter1() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter2() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter3() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter4() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter5() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter6() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter7() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter8() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter9() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter10() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter11() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter12() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter13() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter14() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter15() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter16() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter17() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter18() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter19() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter20() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

Function diameter21() -> Nothing:
Begin

  Let maximum be 0

  For w in BFT(T,v):
  Begin
    If Depth > maximum:
    Begin
      Let maximum be Depth
      Let farthest be w
    End
  End

  Let maximum be 0

  For w in BFT(T,farthest):
  Begin
    Let maximum be Depth
  End
  return Nothing
End

