# This program is meant to test comments
Define Vertex V
Define Graph G
# Test comment immediately after code line
   
# Random spaces on next line -- should be ignored
      
# Testing comment after multiple spaces and newlines
# Testing back-to-back comments

Define Int x

# Code line with trailing spaces -- should not be a problem
Let x be 10 + 25   

If x > 0 :
# If the test cocndition is true
Begin
  Let x be 0 - 1
End

# Comments at the end of the file

